version: "3.8"

services:
  app:
    build: .
    ports:
      - "5255:5255"   # Expondo a porta 5255
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # ou Production, conforme necessário
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge